name: Ejecucion Diaria Bot Polla

on:
  schedule:
    # 14:45 UTC equivale a las 9:45 AM (Hora Colombia)
    - cron: '45 14 * * *'
  workflow_dispatch:

jobs:
  correr-script:
    runs-on: ubuntu-latest
    
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: 'true'

    steps:
      - name: Traer el código del repositorio
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar la librería de Gemini
        run: pip install google-genai

      - name: Ejecutar el bot de pronósticos
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
          MI_CORREO: ${{ secrets.MI_CORREO }}
          DESTINATARIOS: ${{ secrets.DESTINATARIOS }}
        run: python main.py
